### ISSUE TITLE
Emulator error when initializing the environment.

### ISSUE THREAD

**Issue by hejujie** [M-J-Murray/MAMEToolkit#16]
I am running the start up code in readme,  I download roms in freeroms.com and replace the path as absolute path. 
```python
import random
from MAMEToolkit.sf_environment import Environment

roms_path = "/home/leafzs/software/roms/sfiii3"  # Replace this with the path to your ROMs
env = Environment("env1", roms_path)
env.start()
while True:
    move_action = random.randint(0, 8)
    attack_action = random.randint(0, 9)
    frames, reward, round_done, stage_done, game_done = env.step(move_action, attack_action)
    if game_done:
        env.new_game()
    elif stage_done:
        env.next_stage()
    elif round_done:
        env.next_round()
```
One mistake happened, I think the problem may come from emulator. Whether I need to install MAME in github? or there are other reason for that.
```shell
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  100
  Current serial number in output stream:  101
Traceback (most recent call last):
  File "start_up.py", line 5, in <module>
    env = Environment("env1", roms_path)
  File "/home/leafzs/.local/lib/python3.6/site-packages/MAMEToolkit/sf_environment/Environment.py", line 70, in __init__
    self.emu = Emulator(env_id, roms_path, "sfiii3n", setup_memory_addresses(), frame_ratio=frame_ratio, render=render, throttle=throttle, debug=debug)
  File "/home/leafzs/.local/lib/python3.6/site-packages/MAMEToolkit/emulator/Emulator.py", line 51, in __init__
    self.wait_for_resource_registration()
  File "/home/leafzs/.local/lib/python3.6/site-packages/MAMEToolkit/emulator/Emulator.py", line 97, in wait_for_resource_registration
    result = self.console.writeln('print(manager:machine().devices[":maincpu"].spaces["program"])', expect_output=True, timeout=3, raiseError=False)
  File "/home/leafzs/.local/lib/python3.6/site-packages/MAMEToolkit/emulator/Console.py", line 64, in writeln
    self.process.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/leafzs/.local/lib/python3.6/site-packages/MAMEToolkit/emulator/Emulator.py", line 159, in close
    self.actionPipe.close()
AttributeError: 'Emulator' object has no attribute 'actionPipe'
```

my roms file is like this, are there something wrong?
```shell
10  20  29f400.u2  30  31  40  41  50  51  60  61
```
![image](https://user-images.githubusercontent.com/29149911/60077115-cdad1000-975b-11e9-9526-25b7de0ace21.png)

**Comment by guanzeying** [comment]
roms_path = "/home/leafzs/software/roms/sfiii3"
change to 
roms_path = "/home/leafzs/software/roms/"
