### ISSUE TITLE
get gemini wing actions fail

### ISSUE THREAD

**Issue by guanzeying** [M-J-Murray/MAMEToolkit#20]
I use the list actions command:

from MAMEToolkit.emulator import list_actions

roms_path = "roms/"  # Replace this with the path to your ROMs
game_id = "sfiii3n"
print(list_actions(roms_path, game_id))

I get:
[{'port': ':INPUTS', 'field': 'P2 Strong Punch'}, {'port': ':INPUTS', 'field': 'P1 Strong Punch'}, {'port': ':INPUTS', 'field': 'P2 Left'}, {'port': ':INPUTS', 'field': 'Service Mode'}, {'port': ':INPUTS', 'field': 'P2 Up'}, {'port': ':INPUTS', 'field': 'P1 Up'}, {'port': ':INPUTS', 'field': 'P1 Fierce Punch'}, {'port': ':INPUTS', 'field': 'P1 Jab Punch'}, {'port': ':INPUTS', 'field': 'P2 Jab Punch'}, {'port': ':INPUTS', 'field': 'P2 Down'}, {'port': ':INPUTS', 'field': 'P1 Down'}, {'port': ':INPUTS', 'field': 'P2 Fierce Punch'}, {'port': ':INPUTS', 'field': '2 Players Start'}, {'port': ':INPUTS', 'field': 'Coin 2'}, {'port': ':INPUTS', 'field': 'Service 1'}, {'port': ':INPUTS', 'field': '1 Player Start'}, {'port': ':INPUTS', 'field': 'P2 Roundhouse Kick'}, {'port': ':INPUTS', 'field': 'Coin 1'}, {'port': ':INPUTS', 'field': 'P1 Left'}, {'port': ':INPUTS', 'field': 'P2 Right'}, {'port': ':INPUTS', 'field': 'P1 Right'}, {'port': ':scsi:1:cdrom:SCSI_ID', 'field': 'SCSI ID'}, {'port': ':EXTRA', 'field': 'P2 Short Kick'}, {'port': ':EXTRA', 'field': 'P1 Short Kick'}, {'port': ':EXTRA', 'field': 'P1 Forward Kick'}, {'port': ':EXTRA', 'field': 'P2 Forward Kick'}, {'port': ':EXTRA', 'field': 'P1 Roundhouse Kick'}]

When I change game_id.
game_id = "gemini"
I get:
Expected output but received nothing from emulator after 'for k,v in pairs(iop.ports[':SYS_0'].fields) do print(k) end'
Traceback (most recent call last):
  File "list_actions.py", line 7, in <module>
    print(list_actions(roms_path, game_id))
  File "/usr/local/lib/python3.6/site-packages/MAMEToolkit/emulator/Emulator.py", line 21, in list_actions
    fields = console.writeln("for k,v in pairs(iop.ports['"+port+"'].fields) do print(k) end", expect_output=True)
  File "/usr/local/lib/python3.6/site-packages/MAMEToolkit/emulator/Console.py", line 71, in writeln
    raise IOError(error)
OSError: Expected output but received nothing from emulator after 'for k,v in pairs(iop.ports[':SYS_0'].fields) do print(k) end'

How should I solve this problem?

**Comment by guanzeying** [comment]
I change list_actions, Console() use render=True, throttle=True, debug=True, Try more time, I can get it.
